### ISSUE TITLE
What to do with when the image is scheduled for processing?

### ISSUE THREAD

**Issue by yellow1912** [short-pixel-optimizer/shortpixel-php#22]
Assuming that I want to grab the buffer without saving the files to any folder, what should I do when I run into the message "Image scheduled for processing". Should I keep re-trying?

My current code looks like this:

```
if (\ShortPixel\ShortPixel::isProcessable($filePath)) {
            \ShortPixel\setKey(SHORTPIXEL_APIKEY);
            \ShortPixel\ShortPixel::setOptions(["wait" => 300]);

            $result = \ShortPixel\fromBuffer($destinationName, $imageContent)->refresh()->optimize(2)->execute(300);

            if ('Success' === $result->body[0]->Status->Message) {
                $lossyContent = file_get_contents($result->body[0]->LossyURL);

                if ($lossyContent) {
                    $image = $this->imagine->load($lossyContent);
                }
            } elseif ($this->logger) {
                $this->logger->warning(sprintf('ShortPixel failed to process image. Message: %s', $result->body[0]->Status->Message));
            }
        }
```

Perhaps I can retry the same file after say 5 seconds when I get the error?

**Comment by short-pixel-optimizer** [comment]
The API returns this message together with an OriginalURL that it creates for the uploaded image and acts as a reference of the optimization in progress. You can then call the API again using that URL after a while to check if the image is ready, like this:

`ShortPixel\fromUrls($OriginalURL)->optimize(2)->execute(300)`

When you check the status of the already uploaded image, don't use refresh() because this will restart the optimization (as if the image at OriginalURL was changed in the meantime).
